{{- if eq .Values.persistence.claimName "" }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.userName }}-data
  labels:
    app: "code-server"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}

{{- if .Values.persistence.config.storageClassName }}
  storageClassName: {{ .Values.persistence.config.storageClassName }}
{{- end }}
{{- end }}