apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "srvd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "srvd.name" . }}
    helm.sh/chart: {{ include "srvd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "srvd.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "srvd.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- if .Values.hostnameOverride }}
      hostname: {{ .Values.hostnameOverride }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: USER_NAME
            value: {{ .Values.userName }}
          {{- if .Values.extraVars }}
{{ toYaml .Values.extraVars | indent 10 }}
          {{- end }}
          {{- if .Values.extraArgs }}
          args:
{{ toYaml .Values.extraArgs | indent 10 }}
          {{- end }}
          {{ if .Values.userName }}
          volumeMounts:
          - name: data
            mountPath: /home/{{ .Values.userName }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "srvd.serviceAccountName" . }}
      {{ if .Values.persistence }}
      volumes:
      - name: data
        persistentVolumeClaim:
          {{- if eq .Values.persistence.claimName "" }}
          claimName: {{ .Values.userName }}-data
          {{- else }}
          claimName: {{ .Values.persistence.claimName }}
          {{- end }}
      {{- end }}