{{- $root := . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gameServer.gameType }}
  labels:
    gamename: "{{ .Values.deploymentLabels.gameName }}"
    custguild: "{{ .Values.deploymentLabels.customerGuildID }}"
    app: {{ .Values.gameServer.gameType }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.gameServer.gameType }}
  template:
    metadata:
      labels:
        app: {{ .Values.gameServer.gameType }}
    spec:
      securityContext:
        runAsUser: {{ .Values.gameServer.user }}
        runAsGroup: {{ .Values.gameServer.group }}
      initContainers:
{{ if .Values.persistence }}
{{- range $k, $v := .Values.persistence }}
      - name: volume-mount-hack-{{ $root.Values.gameServer.gameType }}-{{ $k }}
        image: busybox
        command: ["sh", "-c", "chown -R {{ .Values.gameServer.user }}:{{ .Values.gameServer.group }} {{ $v.mountpoint }}"]
        volumeMounts:
        - name: {{ $k }}
          mountPath: {{ $v.mountpoint }}
{{- end }}
{{- end }}
      containers:
      - name: {{ .Values.gameServer.gameType }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
          {{- if .Values.env }}
{{ toYaml .Values.env | indent 10 }}
          {{- end }}
        ports:
        {{ if .Values.gameServer.ports.tcp }}
        {{- range .Values.gameServer.ports.tcp }}
        - name: tcp-{{ . }}
          containerPort: {{ . }}
          protocol: TCP
        {{- end }}
        {{- end }}
        {{ if .Values.gameServer.ports.udp }}
        {{- range .Values.gameServer.ports.udp }}
        - name: udp-{{ . }}
          containerPort: {{ . }}
          protocol: UDP
        {{- end }}
        {{- end }}
        volumeMounts:
{{ if .Values.persistence }}
{{- range $k, $v := .Values.persistence }}
        - name: {{ $k }}
          mountPath: {{ $v.mountpoint }}
{{- end }}
{{- end }}
      volumes:
{{ if .Values.persistence }}
{{- range $k, $v := .Values.persistence }}
      - name: {{ $k }}
        persistentVolumeClaim:
{{- if $v.claimName }}
          claimName: {{ $v.claimName }}
{{- else }}
          claimName: {{ $root.Values.gameServer.gameType }}-{{ $k }}
{{- end }}
{{- end }}
{{- end }}