{{ if .Values.persistence }}
{{- if eq .claimName "" }}
{{- range $k, $v := .Values.persistence }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.gameServer.gameType }}-{{ $k }}
  labels:
    app: {{ .Values.gameServer.gameType }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $v.size | quote }}

{{- if $v.storageClassName }}
  storageClassName: {{ $v.storageClassName }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}