{{- $root := . -}}

{{ if .Values.persistence }}
{{- if eq .claimName "" }}
{{- range .Values.persistence }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $root.Values.gameServer.gameType }}-{{ . }}
  labels:
    app: {{ $root.Values.gameServer.gameType }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size | quote }}

{{- if .storageClassName }}
  storageClassName: {{ .storageClassName }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}